version: 0.0
os: linux
files:
  - source: /deployment
    destination: /tmp/
hooks:
  AfterInstall:
    - location: scripts/install_artifacts
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

